### ISSUE TITLE
IndexOutOfRangeException when parsing a given polyline

### ISSUE THREAD

**Issue by SamVanhoutte** [sglogowski/Polyliner.NET#1]
Hello

I was using your library (thanks for that), but for one of the polylines, I wanted to parse, a `System.IndexOutOfRangeException` Exception was thrown.  The test below can be used to repro

It seems the `while (b >= 0x1f);` loop is not exiting in this specific case

I would be happy to fix/contribute, but the details on the Polyline parsing are unknown to me.

```csharp
[Theory]
[InlineData("wvduHmyjU_CbAi@R_@FiAJkCz@cBd@{@T]Bu@Pq@TeAd@q@b@u@\\\\mAt@i@^aCtB[^Wf@w@bCI^Kv@A`AEh@]zBU`CKf@GPQTcA`A")]     
public void Polyliner_Decode_ShouldNotThrowException(string polyline)
{
    // arrange
    var polyliner = new Polyliner();

    // act
    var result = polyliner.Decode(polyline);

    // assert
    Assert.NotNull(result);
}
```

**Comment by sglogowski** [comment]
Hello Sam,

first thanks for yours test case and well described issue. I am working on that now. 

I have one question to you, maybe you have points values that are serialized int this polyline? It would realy help me with debugging.

Sebastian

**Comment by SamVanhoutte** [comment]
Sorry Sebastien for the late reply, I must've missed this notification. 
I will give it a try !  Thanks for the effort !
